#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["beautifulsoup4", "markdownify"]
# ///
from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
import time
import xml.etree.ElementTree as ET
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen

from bs4 import BeautifulSoup, Tag
from markdownify import markdownify as html_to_markdown


DOCS_ORIGIN = "https://developers.openai.com"
API_REFERENCE_PREFIX = "/api/reference"
SITEMAP_INDEX_URL = f"{DOCS_ORIGIN}/sitemap-index.xml"
SITEMAP_NAMESPACE = {"sm": "http://www.sitemaps.org/schemas/sitemap/0.9"}
REQUEST_HEADERS = {
    "User-Agent": "OpenAIDocSync/1.0 (+https://developers.openai.com/api/reference/overview)",
}
EXTRA_ROUTES = (
    "/api/reference/overview",
)
WRAPPER_SEGMENTS = {"resources", "subresources"}
ANCHOR_LINK_CLASS = "sl-anchor-link"
STUB_SENTINEL = "This API reference page is generated by Stainless."
UNAVAILABLE_METHOD_SENTINEL = "is not available in this language"


@dataclass(slots=True)
class FetchResult:
    text: str
    final_url: str
    content_type: str


@dataclass(slots=True)
class SyncResult:
    route: str
    output_path: Path
    source_url: str | None = None
    source_kind: str | None = None
    error: str | None = None

    @property
    def ok(self) -> bool:
        return self.error is None


@dataclass(slots=True)
class PageResult:
    route: str
    content: str | None = None
    source_url: str | None = None
    source_kind: str | None = None
    error: str | None = None

    @property
    def ok(self) -> bool:
        return self.error is None and self.content is not None


@dataclass(slots=True)
class RouteTarget:
    output_path: Path
    fragment: str | None = None


@dataclass(slots=True)
class CollapsedRouteHierarchy:
    root_route: str
    route_depths: dict[str, int]
    children_by_parent: dict[str, list[str]]
    fragments: dict[str, str]


def fetch(url: str, timeout: float, retries: int, retry_delay: float) -> FetchResult:
    last_error: Exception | None = None
    for attempt in range(1, retries + 1):
        request = Request(url, headers=REQUEST_HEADERS)
        try:
            with urlopen(request, timeout=timeout) as response:
                return FetchResult(
                    text=response.read().decode("utf-8", errors="replace"),
                    final_url=response.geturl(),
                    content_type=response.headers.get_content_type(),
                )
        except HTTPError as exc:
            last_error = exc
            if exc.code in {404, 410}:
                raise
        except URLError as exc:
            last_error = exc

        if attempt < retries:
            time.sleep(retry_delay * attempt)

    assert last_error is not None
    raise last_error


def normalize_reference_route(candidate: str) -> str | None:
    parsed = urlparse(candidate)
    if parsed.scheme and parsed.netloc and parsed.netloc != "developers.openai.com":
        return None

    path = parsed.path.rstrip("/")
    if not path:
        return None
    if path == API_REFERENCE_PREFIX:
        return None
    if not path.startswith(f"{API_REFERENCE_PREFIX}/"):
        return None
    return path


def transform_route_segments(route: str) -> tuple[str, ...]:
    relative = route.removeprefix(API_REFERENCE_PREFIX).strip("/")
    parts = [part for part in relative.split("/") if part]
    transformed = [part for part in parts if part not in WRAPPER_SEGMENTS]
    return tuple(("reference", *transformed))


def build_has_children(route_parts: Iterable[tuple[str, ...]]) -> set[tuple[str, ...]]:
    has_children: set[tuple[str, ...]] = set()
    for parts in route_parts:
        for prefix_length in range(1, len(parts)):
            has_children.add(parts[:prefix_length])
    return has_children


def output_path_for(route: str, output_dir: Path, has_children: set[tuple[str, ...]]) -> Path:
    parts = transform_route_segments(route)
    if not parts:
        raise ValueError(f"Unsupported reference route: {route}")

    base_path = output_dir.joinpath(*parts)
    is_overview = parts[-1] == "overview"
    if parts in has_children and not is_overview:
        return base_path / "index.md"
    return base_path.with_suffix(".md")


def route_sort_key(route: str) -> tuple[tuple[str, ...], str]:
    return transform_route_segments(route), route


def transformed_route_lookup(routes: Iterable[str]) -> dict[tuple[str, ...], str]:
    lookup: dict[tuple[str, ...], str] = {}
    for route in routes:
        lookup[transform_route_segments(route)] = route
    return lookup


def discover_routes(timeout: float, retries: int, retry_delay: float) -> list[str]:
    index_xml = fetch(SITEMAP_INDEX_URL, timeout=timeout, retries=retries, retry_delay=retry_delay).text
    index_root = ET.fromstring(index_xml)

    sitemap_urls = [
        node.text.strip()
        for node in index_root.findall("sm:sitemap/sm:loc", SITEMAP_NAMESPACE)
        if node.text and node.text.strip()
    ]
    if not sitemap_urls:
        raise ValueError("No sitemap URLs were found in the OpenAI sitemap index")

    routes: set[str] = set()
    for sitemap_url in sitemap_urls:
        sitemap_xml = fetch(sitemap_url, timeout=timeout, retries=retries, retry_delay=retry_delay).text
        sitemap_root = ET.fromstring(sitemap_xml)
        for loc in sitemap_root.findall("sm:url/sm:loc", SITEMAP_NAMESPACE):
            if not loc.text:
                continue
            normalized = normalize_reference_route(loc.text)
            if normalized:
                routes.add(normalized)

    for extra_route in EXTRA_ROUTES:
        normalized = normalize_reference_route(extra_route)
        if normalized:
            routes.add(normalized)

    if not routes:
        raise ValueError("No /api/reference routes were discovered from the OpenAI sitemaps")

    return sorted(routes, key=route_sort_key)


def candidate_markdown_urls(route: str) -> list[str]:
    if route.endswith("/overview"):
        return [
            f"{DOCS_ORIGIN}{route}.md",
            f"{DOCS_ORIGIN}{route}/index.md",
        ]

    return [
        f"{DOCS_ORIGIN}{route}/index.md",
        f"{DOCS_ORIGIN}{route}.md",
    ]


def is_html(text: str) -> bool:
    stripped = text.lstrip()
    return stripped.startswith("<!DOCTYPE html") or stripped.startswith("<html")


def is_stub_markdown(text: str) -> bool:
    if STUB_SENTINEL not in text:
        return False
    non_empty_lines = [line for line in text.splitlines() if line.strip()]
    return len(non_empty_lines) <= 8


def select_content_root(soup: BeautifulSoup) -> Tag:
    candidates = soup.select("main .sl-markdown-content .not-content")
    for candidate in candidates:
        if candidate.find(["h1", "h2"]):
            return candidate

    fallback = soup.select_one("main .sl-markdown-content")
    if isinstance(fallback, Tag):
        return fallback

    raise ValueError("Could not find the OpenAI reference content container in the HTML page")


def html_reference_to_markdown(html: str) -> str:
    soup = BeautifulSoup(html, "html.parser")
    root = select_content_root(soup)

    for element in root.select(
        ",".join(
            (
                "script",
                "style",
                "svg",
                f"a.{ANCHOR_LINK_CLASS}",
            )
        )
    ):
        element.decompose()

    return html_to_markdown(
        str(root),
        heading_style="ATX",
        bullets="-",
    )


def strip_non_gfm_artifacts(content: str) -> str:
    content = content.replace("\r\n", "\n")
    content = re.sub(r"<!--.*?-->", "", content, flags=re.DOTALL)
    content = re.sub(r"^\s*\{/\*.*?\*/\}\s*\n?", "\n\n", content, flags=re.MULTILINE)
    content = re.sub(r"[ \t]+\n", "\n", content)
    content = re.sub(r"\n{3,}", "\n\n", content)
    return content.strip() + "\n"


def normalize_heading_levels(content: str) -> str:
    lines = content.splitlines()
    normalized: list[str] = []
    in_code_block = False
    seen_h1 = False

    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_code_block = not in_code_block
            normalized.append(line)
            continue

        if not in_code_block and line.startswith("# "):
            if seen_h1:
                normalized.append(f"## {line[2:]}")
            else:
                normalized.append(line)
                seen_h1 = True
            continue

        normalized.append(line)

    return "\n".join(normalized)


def normalize_same_origin_link(destination: str) -> tuple[str | None, str | None, str | None]:
    parsed = urlparse(destination)
    if parsed.scheme and parsed.netloc and parsed.netloc != "developers.openai.com":
        return None, None, None

    path = parsed.path
    normalized_route = normalize_reference_route(path)
    return normalized_route, parsed.query or None, parsed.fragment or None


def rewrite_destination(destination: str, current_output: Path, route_targets: dict[str, RouteTarget]) -> str:
    normalized_route, query, fragment = normalize_same_origin_link(destination)
    if normalized_route and normalized_route in route_targets:
        target = route_targets[normalized_route]
        relative = os.path.relpath(target.output_path, current_output.parent).replace(os.sep, "/")
        effective_fragment = fragment or target.fragment
        suffix = ""
        if query:
            suffix += f"?{query}"
        if effective_fragment:
            suffix += f"#{effective_fragment}"
        return f"{relative}{suffix}"

    parsed = urlparse(destination)
    if destination.startswith("/") and not parsed.scheme and not parsed.netloc:
        return f"{DOCS_ORIGIN}{destination}"

    return destination


def rewrite_links(content: str, current_output: Path, route_targets: dict[str, RouteTarget]) -> str:
    link_pattern = re.compile(
        r"(?P<prefix>!?\[[^\]]*]\()(?P<destination>[^)\s]+)(?P<suffix>\))"
    )
    autolink_pattern = re.compile(
        r"(?P<prefix><)(?P<destination>https://developers\.openai\.com[^>\s]+|/[^>\s]+)(?P<suffix>>)"
    )

    def replace_link(match: re.Match[str]) -> str:
        rewritten = rewrite_destination(match.group("destination"), current_output, route_targets)
        return f"{match.group('prefix')}{rewritten}{match.group('suffix')}"

    content = link_pattern.sub(replace_link, content)
    content = autolink_pattern.sub(replace_link, content)
    return content


def fetch_markdown_or_html(
    route: str,
    timeout: float,
    retries: int,
    retry_delay: float,
) -> tuple[str, str, str]:
    for candidate_url in candidate_markdown_urls(route):
        try:
            fetched = fetch(candidate_url, timeout=timeout, retries=retries, retry_delay=retry_delay)
        except HTTPError as exc:
            if exc.code in {404, 410}:
                continue
            raise

        if fetched.content_type == "text/markdown" and not is_html(fetched.text):
            if is_stub_markdown(fetched.text):
                continue
            return fetched.text, fetched.final_url, "markdown"

    html_route = f"{DOCS_ORIGIN}{route}"
    fetched_html = fetch(html_route, timeout=timeout, retries=retries, retry_delay=retry_delay)
    markdown = html_reference_to_markdown(fetched_html.text)
    return markdown, fetched_html.final_url, "html"


def fetch_one(
    route: str,
    timeout: float,
    retries: int,
    retry_delay: float,
) -> PageResult:
    try:
        content, source_url, source_kind = fetch_markdown_or_html(
            route=route,
            timeout=timeout,
            retries=retries,
            retry_delay=retry_delay,
        )
        content = strip_non_gfm_artifacts(content)
        content = normalize_heading_levels(content)
        return PageResult(
            route=route,
            content=content,
            source_url=source_url,
            source_kind=source_kind,
        )
    except Exception as exc:  # noqa: BLE001
        return PageResult(route=route, error=str(exc))


def is_method_route(route: str) -> bool:
    return "/methods/" in route


def parent_route_for_method(route: str) -> str | None:
    prefix, separator, _ = route.partition("/methods/")
    if not separator:
        return None
    return prefix


def parent_route_for_non_method_route(
    route: str,
    transformed_lookup: dict[tuple[str, ...], str],
) -> str | None:
    parts = transform_route_segments(route)
    if len(parts) <= 2:
        return None

    return transformed_lookup.get(parts[:-1])


def first_heading_title(content: str) -> str | None:
    match = re.search(r"^\#{1,6}\s+(.+?)\s*$", content, flags=re.MULTILINE)
    if not match:
        return None
    title = match.group(1).strip()
    title = re.sub(r"`([^`]*)`", r"\1", title)
    title = re.sub(r"<[^>]+>", "", title)
    return title or None


def github_anchor_slug(title: str) -> str:
    slug = title.strip().lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = slug.replace("_", "-")
    slug = re.sub(r"\s+", "-", slug)
    slug = re.sub(r"-{2,}", "-", slug)
    return slug.strip("-")


def unavailable_method_slug(content: str) -> str | None:
    if UNAVAILABLE_METHOD_SENTINEL not in content:
        return None

    match = re.search(
        r"The method `(?P<method>[^`]+)` is not available in this language\.",
        content,
    )
    if not match:
        return None

    return github_anchor_slug(match.group("method"))


def content_has_heading_slug(content: str, expected_slug: str) -> bool:
    for match in re.finditer(r"^\#{1,6}\s+(.+?)\s*$", content, flags=re.MULTILINE):
        if github_anchor_slug(match.group(1)) == expected_slug:
            return True
    return False


def detect_redundant_routes(
    page_results: dict[str, PageResult],
    transformed_lookup: dict[tuple[str, ...], str],
) -> dict[str, tuple[str, str]]:
    redundant: dict[str, tuple[str, str]] = {}
    for route, page_result in page_results.items():
        if not page_result.ok or not page_result.content:
            continue

        parent_route: str | None
        if is_method_route(route):
            parent_route = parent_route_for_method(route)
        else:
            parent_route = parent_route_for_non_method_route(
                route,
                transformed_lookup=transformed_lookup,
            )
        if not parent_route:
            continue

        parent_result = page_results.get(parent_route)
        if parent_result is None or not parent_result.ok or not parent_result.content:
            continue

        unavailable_slug = unavailable_method_slug(page_result.content)
        if unavailable_slug is not None:
            fragment = unavailable_slug if content_has_heading_slug(parent_result.content, unavailable_slug) else ""
            redundant[route] = (parent_route, fragment)
            continue

        if page_result.content not in parent_result.content:
            continue

        heading_title = first_heading_title(page_result.content)
        if not heading_title:
            continue

        redundant[route] = (parent_route, github_anchor_slug(heading_title))

    return redundant


def resolve_route_target(
    route: str,
    redundant_routes: dict[str, tuple[str, str]],
    final_output_paths: dict[str, Path],
) -> RouteTarget:
    if route not in redundant_routes:
        return RouteTarget(output_path=final_output_paths[route])

    parent_route, fragment = redundant_routes[route]
    resolved_parent = resolve_route_target(parent_route, redundant_routes, final_output_paths)
    return RouteTarget(output_path=resolved_parent.output_path, fragment=fragment or None)


def build_collapsed_route_hierarchies(
    routes: Iterable[str],
    surviving_routes: Iterable[str],
    redundant_routes: dict[str, tuple[str, str]],
    route_targets: dict[str, RouteTarget],
    final_output_paths: dict[str, Path],
) -> dict[str, CollapsedRouteHierarchy]:
    surviving_roots_by_output = {
        final_output_paths[route].resolve(): route
        for route in surviving_routes
    }

    routes_by_root: dict[str, list[str]] = {route: [] for route in surviving_roots_by_output.values()}
    for route in routes:
        target_root = surviving_roots_by_output.get(route_targets[route].output_path.resolve())
        if target_root is None:
            continue
        routes_by_root[target_root].append(route)

    hierarchies: dict[str, CollapsedRouteHierarchy] = {}
    for root_route, member_routes in routes_by_root.items():
        route_depths: dict[str, int] = {root_route: 0}
        children_by_parent: dict[str, list[str]] = {}
        fragments: dict[str, str] = {}

        def assign(route: str) -> None:
            if route in route_depths:
                return

            parent_route, fragment = redundant_routes[route]
            assign(parent_route)
            route_depths[route] = route_depths[parent_route] + 1
            fragments[route] = fragment
            children = children_by_parent.setdefault(parent_route, [])
            if route not in children:
                children.append(route)

        for route in member_routes:
            if route == root_route or route not in redundant_routes:
                continue
            assign(route)

        hierarchies[root_route] = CollapsedRouteHierarchy(
            root_route=root_route,
            route_depths=route_depths,
            children_by_parent=children_by_parent,
            fragments=fragments,
        )

    return hierarchies


def compute_final_output_paths(
    surviving_routes: Iterable[str],
    base_output_paths: dict[str, Path],
    reference_root: Path,
) -> dict[str, Path]:
    final_paths = {route: base_output_paths[route] for route in surviving_routes}

    changed = True
    while changed:
        changed = False
        for route, path in sorted(final_paths.items(), key=lambda item: (len(item[1].parts), str(item[1])), reverse=True):
            if path.name != "index.md":
                continue

            directory = path.parent
            if directory == reference_root:
                continue

            other_paths = [other for other_route, other in final_paths.items() if other_route != route]
            has_other_inside_dir = any(
                other == directory
                or directory in other.parents
                or other.parent == directory
                for other in other_paths
            )
            if has_other_inside_dir:
                continue

            flattened = directory.with_suffix(".md")
            if any(other == flattened for other in other_paths):
                continue

            final_paths[route] = flattened
            changed = True

    return final_paths


def prune_empty_directories(start_dir: Path, stop_dir: Path) -> None:
    current = start_dir
    stop_dir = stop_dir.resolve()
    while current.exists() and current.resolve() != stop_dir:
        try:
            current.rmdir()
        except OSError:
            break
        current = current.parent


def normalize_route_heading_hierarchy(content: str, hierarchy: CollapsedRouteHierarchy) -> str:
    if not hierarchy.children_by_parent:
        return content

    heading_pattern = re.compile(r"^(#{1,6})\s+(.*)$")
    lines = content.splitlines()
    normalized: list[str] = []
    in_code_block = False
    seen_root_heading = False
    seen_children = {route: set[str]() for route in hierarchy.route_depths}
    stack: list[tuple[str, int]] = [(hierarchy.root_route, 1)]

    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_code_block = not in_code_block
            normalized.append(line)
            continue

        match = heading_pattern.match(line) if not in_code_block else None
        if match is None:
            normalized.append(line)
            continue

        level = len(match.group(1))
        title = match.group(2)
        slug = github_anchor_slug(title)

        if level == 1 and not seen_root_heading:
            seen_root_heading = True
            stack = [(hierarchy.root_route, 1)]
            normalized.append(line)
            continue

        matched_route: tuple[int, str] | None = None
        for stack_index in range(len(stack) - 1, -1, -1):
            parent_route = stack[stack_index][0]
            for child_route in hierarchy.children_by_parent.get(parent_route, []):
                if child_route in seen_children[parent_route]:
                    continue
                if hierarchy.fragments.get(child_route) == slug:
                    matched_route = (stack_index, child_route)
                    break
            if matched_route is not None:
                break

        if matched_route is not None:
            stack_index, child_route = matched_route
            parent_route = stack[stack_index][0]
            seen_children[parent_route].add(child_route)
            stack = stack[: stack_index + 1]
            desired_level = min(hierarchy.route_depths[child_route] + 1, 6)
            stack.append((child_route, level))
            normalized.append(f"{'#' * desired_level} {title}")
            continue

        current_route, current_level = stack[-1]
        desired_route_level = min(hierarchy.route_depths[current_route] + 1, 6)
        adjusted_level = max(level + (desired_route_level - current_level), desired_route_level + 1)
        adjusted_level = max(1, min(adjusted_level, 6))
        normalized.append(f"{'#' * adjusted_level} {title}")

    return "\n".join(normalized) + "\n"


def write_one(
    page_result: PageResult,
    output_path: Path,
    route_targets: dict[str, RouteTarget],
    hierarchy: CollapsedRouteHierarchy,
) -> SyncResult:
    assert page_result.content is not None
    try:
        content = normalize_route_heading_hierarchy(page_result.content, hierarchy)
        content = rewrite_links(content, current_output=output_path, route_targets=route_targets)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
        return SyncResult(
            route=page_result.route,
            output_path=output_path,
            source_url=page_result.source_url,
            source_kind=page_result.source_kind,
        )
    except Exception as exc:  # noqa: BLE001
        return SyncResult(route=page_result.route, output_path=output_path, error=str(exc))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync the OpenAI API reference into local GitHub-flavored Markdown files."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="Directory that receives the generated Markdown tree.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=16,
        help="Number of concurrent page fetches.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        help="Only sync the first N discovered routes. Useful for smoke tests.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=30.0,
        help="Per-request timeout in seconds.",
    )
    parser.add_argument(
        "--retries",
        type=int,
        default=3,
        help="Number of attempts for each request.",
    )
    parser.add_argument(
        "--retry-delay",
        type=float,
        default=0.5,
        help="Base delay in seconds between retry attempts.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove the generated ./reference tree before writing fresh output.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print every file as it is written.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    routes = discover_routes(timeout=args.timeout, retries=args.retries, retry_delay=args.retry_delay)
    if args.limit is not None:
        routes = routes[: args.limit]

    transformed_routes = {route: transform_route_segments(route) for route in routes}
    has_children = build_has_children(transformed_routes.values())
    route_output_paths = {
        route: output_path_for(route, output_dir=output_dir, has_children=has_children)
        for route in routes
    }
    transformed_lookup = transformed_route_lookup(routes)

    reference_root = output_dir / "reference"
    if args.clean and reference_root.exists():
        shutil.rmtree(reference_root)

    fetched_results: list[PageResult] = []
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {
            executor.submit(
                fetch_one,
                route,
                args.timeout,
                args.retries,
                args.retry_delay,
            ): route
            for route in routes
        }

        for future in as_completed(futures):
            result = future.result()
            fetched_results.append(result)
            if args.verbose and result.ok:
                source_kind = result.source_kind or "unknown"
                print(f"[{source_kind}] fetched {result.route}")

    failures = [result for result in fetched_results if not result.ok]
    fetched_ok = [result for result in fetched_results if result.ok]
    markdown_count = sum(1 for result in fetched_ok if result.source_kind == "markdown")
    html_count = sum(1 for result in fetched_ok if result.source_kind == "html")

    if failures:
        print(
            f"Fetched {len(fetched_ok)}/{len(routes)} routes "
            f"({markdown_count} markdown, {html_count} html fallback)."
        )
        print("Failed routes:", file=sys.stderr)
        for result in sorted(failures, key=lambda item: route_sort_key(item.route)):
            print(f"- {result.route}: {result.error}", file=sys.stderr)
        return 1

    page_results_by_route = {result.route: result for result in fetched_ok}
    redundant_routes = detect_redundant_routes(
        page_results_by_route,
        transformed_lookup=transformed_lookup,
    )

    surviving_routes = [route for route in routes if route not in redundant_routes]
    final_output_paths = compute_final_output_paths(
        surviving_routes=surviving_routes,
        base_output_paths=route_output_paths,
        reference_root=reference_root,
    )

    route_targets = {
        route: resolve_route_target(
            route,
            redundant_routes=redundant_routes,
            final_output_paths=final_output_paths,
        )
        for route in routes
    }
    collapsed_hierarchies = build_collapsed_route_hierarchies(
        routes=routes,
        surviving_routes=surviving_routes,
        redundant_routes=redundant_routes,
        route_targets=route_targets,
        final_output_paths=final_output_paths,
    )

    if not args.clean:
        stale_routes = set(redundant_routes)
        stale_routes.update(
            route
            for route in surviving_routes
            if final_output_paths[route] != route_output_paths[route]
        )
        for route in stale_routes:
            redundant_output = route_output_paths[route]
            if redundant_output.exists():
                redundant_output.unlink()
                prune_empty_directories(redundant_output.parent, stop_dir=output_dir)

    pages_to_write = [
        page_results_by_route[route]
        for route in routes
        if route not in redundant_routes
    ]
    results: list[SyncResult] = []
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {
            executor.submit(
                write_one,
                page_result,
                final_output_paths[page_result.route],
                route_targets,
                collapsed_hierarchies[page_result.route],
            ): page_result.route
            for page_result in pages_to_write
        }

        for future in as_completed(futures):
            result = future.result()
            results.append(result)
            if args.verbose and result.ok:
                source_kind = result.source_kind or "unknown"
                print(f"[{source_kind}] {result.route} -> {result.output_path.relative_to(output_dir)}")

    write_failures = [result for result in results if not result.ok]
    written_ok = [result for result in results if result.ok]
    print(
        f"Synced {len(fetched_ok)}/{len(routes)} routes "
        f"({markdown_count} markdown, {html_count} html fallback, "
        f"{len(redundant_routes)} redundant child pages skipped, "
        f"{len(written_ok)} files written)."
    )

    if write_failures:
        print("Failed routes:", file=sys.stderr)
        for result in sorted(write_failures, key=lambda item: route_sort_key(item.route)):
            print(f"- {result.route}: {result.error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
